name = "kiss-worker"
main = "src/index.js"
compatibility_date = "2025-09-27"
kv_namespaces = [
    { binding = "KV", id = "01d3a47d26ca4732b4e6189b4d095ffe", preview_id = "01d3a47d26ca4732b4e6189b4d095ffe" }
]
